"""kgcs: the deterministic Knowledge Graph Curation core (Sprint 1).

The first curation engine: it begins at the `Candidate` boundary and produces
a complete, immutable `CurationPlan` plus its `ValidationDecision`s,
`ResolutionDecision`s, and `AuditRecord`s — and stops there. Nothing is
written to the graph, no entity resolution runs, and there are no embeddings,
LLMs, or probabilistic behavior. Every output is a pure function of the input
candidates and the injected `IdFactory` (the audit stream additionally of the
injected `Clock`), so identical input yields an identical plan.

    Candidate → Validator → Policy → Planner → Audit

The stages are the modules `validation`, `policy`, `planner`, `audit`, wired
by `engine`. `CurationEngine.create(...)` assembles a coherent default; the
determinism primitives (`clock`, `ids`, `scores`) and the in-memory
`AuditSink` (`memory`) are the injectable seams. Contracts themselves live in
`kg_contracts` (frozen); this package only orchestrates over them.
"""

from kgcs.advisers import (
    Adviser,
    AdviserAssessment,
    AdviserQuestion,
    AssertionAdviser,
    AssertionRecommendation,
    CompletionError,
    CompletionMiss,
    CompletionPort,
    CompletionRequest,
    CompletionResponse,
    CompletionTimeout,
    ConceptEvolutionAdviser,
    ConceptRecommendation,
    ConflictAdviser,
    ConflictRecommendation,
    CurationOrchestrator,
    FailingCompletionClient,
    IdentityAdviser,
    IdentityRecommendation,
    MalformedCompletionClient,
    OntologyEvolutionAdviser,
    OntologyRecommendation,
    OrchestrationResult,
    RecordedCompletionClient,
    StructuredAdviser,
    TimeoutCompletionClient,
)
from kgcs.audit import AuditRecorder, AuditSink
from kgcs.clock import Clock, FixedClock, SystemClock
from kgcs.engine import CandidateOutcome, CurationEngine, EngineResult
from kgcs.er import (
    BlockingPipeline,
    CalibratedMatcher,
    CalibrationKey,
    CalibrationMetrics,
    CalibrationModel,
    CandidatePair,
    Cluster,
    ClusterConstraint,
    ClusterSnapshot,
    ClusterValidation,
    ClusterValidator,
    ConstraintResult,
    DefaultFeatureExtractor,
    DefaultNormalizer,
    DeterministicRuleMatcher,
    EmbeddingChannel,
    ErAction,
    ErDecision,
    ErResolutionPolicy,
    ErRoutingThresholds,
    ExactIdentifierChannel,
    FeatureAgreement,
    GoldenSet,
    IdentityAuthorityConstraint,
    IdentitySignal,
    LabeledPair,
    MatchResult,
    MutuallyExclusiveAttributeConstraint,
    NormalizedEntity,
    NormalizedNameChannel,
    PairFeatures,
    SharedStrongIdentifierRule,
    SourceKeyChannel,
    TemporalConsistencyConstraint,
    TenantBoundaryConstraint,
    UniqueSourceConstraint,
    default_cluster_validator,
    default_source_of,
    evaluate,
    select_survivor,
)
from kgcs.executor import (
    DEFAULT_EXECUTED_BY,
    DEFAULT_SUPPORTED_OPERATIONS,
    INVERSE_OPERATION,
    CompensationResult,
    Compensator,
    EpochPublisher,
    ExecutionAuditSink,
    ExecutionOutcome,
    ExecutionRecord,
    PlanExecutor,
)
from kgcs.ids import DerivedIdFactory, IdFactory, UlidIdFactory, is_well_formed_graph_id
from kgcs.memory import (
    InMemoryAuditSink,
    InMemoryEpochPublisher,
    InMemoryExecutionAuditSink,
)
from kgcs.planner import (
    CurationPlanner,
    PlannedOperation,
    PlanResult,
    ResolvedCandidate,
)
from kgcs.policy import ResolutionPolicy
from kgcs.profiles import (
    CurationProfile,
    ErMode,
    FalseMergeCostClass,
    IdentityAuthorityMode,
    ProfileRegistry,
    ProfileScope,
    client_authoritative_profile,
    default_profile,
    default_registry,
    projection_consumer_profile,
)
from kgcs.recuration import (
    AssertionReassignment,
    ConceptEvolutionPlanner,
    CurationTrigger,
    DependencyIndex,
    EvolutionKind,
    EvolutionResult,
    IllegalOntologyTransition,
    InMemoryDependencyIndex,
    InMemoryTriggerQueue,
    OntologyLifecycle,
    OntologyPromotionRefused,
    OntologyTerm,
    OntologyTermState,
    TriggerKind,
    TriggerQueue,
    VersionContext,
    is_legal_transition,
)
from kgcs.review import (
    BacklogAnalyzer,
    BacklogConfig,
    BackpressureAction,
    BackpressureSignal,
    ClusterBacklog,
    InMemoryReviewStore,
    JsonFileReviewStore,
    PermanentQueueError,
    PersistentReviewQueue,
    QueueMetrics,
    QueueState,
    RetryableQueueError,
    ReviewCase,
    ReviewOperationError,
    ReviewOutcome,
    ReviewOutcomeStatus,
    ReviewProposal,
    ReviewQueueError,
    ReviewRouter,
    ReviewStore,
    SourceBacklog,
    sla_deadline,
    sla_hours,
)
from kgcs.scores import score_vector
from kgcs.validation import (
    CandidateValidator,
    ContractVersionRule,
    GraphIdWellFormedRule,
    GraphScopeRule,
    ProducerPresentRule,
    RuleBasedValidator,
    RuleViolation,
    SupportedKindRule,
    ValidationRule,
    default_validator,
)

__all__ = [
    # engine
    "CurationEngine",
    "EngineResult",
    "CandidateOutcome",
    # stages
    "CandidateValidator",
    "RuleBasedValidator",
    "ValidationRule",
    "RuleViolation",
    "SupportedKindRule",
    "GraphIdWellFormedRule",
    "GraphScopeRule",
    "ContractVersionRule",
    "ProducerPresentRule",
    "default_validator",
    "ResolutionPolicy",
    "CurationPlanner",
    "PlanResult",
    "PlannedOperation",
    "ResolvedCandidate",
    "AuditRecorder",
    "AuditSink",
    # determinism primitives
    "Clock",
    "SystemClock",
    "FixedClock",
    "IdFactory",
    "DerivedIdFactory",
    "UlidIdFactory",
    "is_well_formed_graph_id",
    "score_vector",
    # in-memory adapters
    "InMemoryAuditSink",
    "InMemoryEpochPublisher",
    "InMemoryExecutionAuditSink",
    # entity resolution (Wave 2 / ER 5a, spec §7.4)
    "NormalizedEntity",
    "DefaultNormalizer",
    "FeatureAgreement",
    "IdentitySignal",
    "SharedStrongIdentifierRule",
    "CandidatePair",
    "BlockingPipeline",
    "ExactIdentifierChannel",
    "NormalizedNameChannel",
    "SourceKeyChannel",
    "EmbeddingChannel",
    "PairFeatures",
    "DefaultFeatureExtractor",
    "CalibrationKey",
    "MatchResult",
    "DeterministicRuleMatcher",
    "CalibrationModel",
    "CalibratedMatcher",
    "LabeledPair",
    "GoldenSet",
    "CalibrationMetrics",
    "evaluate",
    # cluster validation (Wave 3 / §7.4 step 5)
    "Cluster",
    "ClusterSnapshot",
    "ClusterConstraint",
    "ConstraintResult",
    "ClusterValidation",
    "ClusterValidator",
    "TemporalConsistencyConstraint",
    "UniqueSourceConstraint",
    "MutuallyExclusiveAttributeConstraint",
    "TenantBoundaryConstraint",
    "IdentityAuthorityConstraint",
    "default_cluster_validator",
    "default_source_of",
    "select_survivor",
    # deterministic ER policy gate (Wave 3 / §7.4 step 6)
    "ErAction",
    "ErDecision",
    "ErResolutionPolicy",
    "ErRoutingThresholds",
    # curation profiles (Wave 3 / DG-5)
    "IdentityAuthorityMode",
    "ErMode",
    "FalseMergeCostClass",
    "ProfileScope",
    "CurationProfile",
    "ProfileRegistry",
    "default_profile",
    "projection_consumer_profile",
    "client_authoritative_profile",
    "default_registry",
    # bounded LLM advisers (Wave 4 / DG-2 / DG-4, spec §7.4)
    "CompletionRequest",
    "CompletionResponse",
    "CompletionPort",
    "RecordedCompletionClient",
    "FailingCompletionClient",
    "TimeoutCompletionClient",
    "MalformedCompletionClient",
    "CompletionError",
    "CompletionTimeout",
    "CompletionMiss",
    "AdviserQuestion",
    "AdviserAssessment",
    "Adviser",
    "StructuredAdviser",
    "IdentityAdviser",
    "IdentityRecommendation",
    "AssertionAdviser",
    "AssertionRecommendation",
    "ConflictAdviser",
    "ConflictRecommendation",
    "ConceptEvolutionAdviser",
    "ConceptRecommendation",
    "OntologyEvolutionAdviser",
    "OntologyRecommendation",
    "CurationOrchestrator",
    "OrchestrationResult",
    # transaction-aware executor + compensation (Wave 1 / Plan 3)
    "PlanExecutor",
    "ExecutionOutcome",
    "ExecutionRecord",
    "ExecutionAuditSink",
    "EpochPublisher",
    "DEFAULT_EXECUTED_BY",
    "DEFAULT_SUPPORTED_OPERATIONS",
    "Compensator",
    "CompensationResult",
    "INVERSE_OPERATION",
    # re-curation + concept/ontology evolution (Wave 5 / DG-1 / DG-3)
    "TriggerKind",
    "VersionContext",
    "CurationTrigger",
    "TriggerQueue",
    "InMemoryTriggerQueue",
    "DependencyIndex",
    "InMemoryDependencyIndex",
    "EvolutionKind",
    "AssertionReassignment",
    "EvolutionResult",
    "ConceptEvolutionPlanner",
    "OntologyTermState",
    "OntologyTerm",
    "OntologyLifecycle",
    "IllegalOntologyTransition",
    "OntologyPromotionRefused",
    "is_legal_transition",
    # review queue + backpressure (Wave 6 / §9 laws 14, 15)
    "PersistentReviewQueue",
    "ReviewStore",
    "InMemoryReviewStore",
    "JsonFileReviewStore",
    "QueueState",
    "ReviewQueueError",
    "RetryableQueueError",
    "PermanentQueueError",
    "ReviewCase",
    "sla_hours",
    "sla_deadline",
    "ReviewRouter",
    "ReviewProposal",
    "ReviewOutcome",
    "ReviewOutcomeStatus",
    "ReviewOperationError",
    "BacklogAnalyzer",
    "BacklogConfig",
    "QueueMetrics",
    "SourceBacklog",
    "ClusterBacklog",
    "BackpressureSignal",
    "BackpressureAction",
    "InMemoryEpochPublisher",
    "InMemoryExecutionAuditSink",
]
